- name: Check Serial
  shell: sed -n 3p /etc/bind/capes.gov.br.hosts
  register: result
  ignore_errors: yes
- debug: msg="{{ result.stdout }}"

- lineinfile:
    path: /etc/bind/capes.gov.br.hosts
    state: present
    regexp: '^\t\t\t2020'
    #insertbefore: '^www.*80/tcp'
    line: "{{ result.stdout | int +1}}"
    register: result
- debug: msg="{{ result.stdout }}"